apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
  namespace: cc2-term-paper-api
  labels:
    deployment: api
    service: api
spec:
  parentRefs:

  - name: external
    namespace: api-gateway
  hostnames:
  - "api.evanhearnesetu.com"
  rules:
  - matches:
    - method: GET
      path:
        type: PathPrefix
        value: "/ping"
    - method: POST
      path:
        type: PathPrefix
        value: "/echo"    
    backendRefs:
    - name: api
      port: 8080  