---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: docker.io/evanhearnesetu/cc2-term-paper-api:latest
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080