apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: external-dnspolicy
  namespace: api-gateway
spec:
  healthCheck:
    failureThreshold: 3
    interval: 1m
    path: /health
  loadBalancing:
    defaultGeo: true
    geo: GEO-NA
    weight: 120
  targetRef:
    name: external
    group: gateway.networking.k8s.io
    kind: Gateway
  providerRefs:

  - name: aws-credentials # Secret created earlier