apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: external-rlp
  namespace: api-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external
  defaults:
    limits:
      "low-limit":
        rates:

        - limit: 1
          window: 10s