apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
spec:
  parentRefs:

  - name: external
    namespace: gateway-system
  - name: internal
    namespace: gateway-system
  hostnames:
  - "*.api.io"
  - "*.api.local"
  rules:
  - backendRefs:
    - name: api
      port: 80