apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
spec:
  parentRefs:

  - name: prod-web
    namespace: my-gateways
  hostnames:
  - "*.api.local"
  rules:
  - matches:
    - method: GET
      path:
        type: PathPrefix
        value: "/ping"  
    backendRefs:
      - name: api
        port: 80